# ShellPoint Docker Compose Configuration
# CognitioLabs (https://cognitiolabs.eu)

version: '3.8'

services:
  shellpoint:
    build:
      context: .
      dockerfile: Dockerfile
    image: cognitiolabs/shellpoint:latest
    container_name: shellpoint
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_PATH=/app/data/ssh-client.db
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      # Persistent database storage
      - shellpoint-data:/app/data
      # Optional: Mount .env file for secrets
      - ./.env:/app/.env:ro
    networks:
      - shellpoint-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.cognitiolabs.description=ShellPoint SSH Client"
      - "com.cognitiolabs.version=1.0.0"

volumes:
  shellpoint-data:
    driver: local

networks:
  shellpoint-network:
    driver: bridge
